const THEMES = {
  defaultLight: {
    '--chat-bg': '#f5f5f5',
    '--bubble-own-bg': '#cce5ff',
    '--bubble-theirs-bg': '#e9ecef',
    '--text-color': '#212529',
    '--header-bg': '#007bff',
    '--header-text': '#ffffff',
    '--input-bg': '#ffffff',
    '--button-bg': '#007bff',
    '--button-hover-bg': '#0056b3',
    '--sidebar-bg': '#ffffff',
    '--sidebar-text': '#212529',
    '--title-text': '#007bff',
    '--btn-secondary-bg': '#6c757d',
    '--btn-secondary-hover-bg': '#5a6268',
  },

  defaultDark: {
    '--chat-bg': '#272727ff',
    '--bubble-own-bg': '#2a9df4',
    '--bubble-theirs-bg': '#0d0d4aff',
    '--text-color': '#f1f1f1',
    '--header-bg': '#0d6efd',
    '--header-text': '#ffffff',
    '--input-bg': '#2a2a2a',
    '--button-bg': '#0d6efd',
    '--button-hover-bg': '#084298',
    '--sidebar-bg': '#1c1c1c',
    '--sidebar-text': '#f1f1f1',
    '--title-text': '#0d6efd',
    '--btn-secondary-bg': '#6c757d',
    '--btn-secondary-hover-bg': '#5a6268',
  },

  blueLight: {
    '--chat-bg': '#e3f2fd',
    '--bubble-own-bg': '#90caf9',
    '--bubble-theirs-bg': '#bbdefb',
    '--text-color': '#0d47a1',
    '--header-bg': '#2196f3',
    '--header-text': '#ffffff',
    '--input-bg': '#ffffff',
    '--button-bg': '#2196f3',
    '--button-hover-bg': '#1976d2',
    '--sidebar-bg': '#bbdefb',
    '--sidebar-text': '#0d47a1',
    '--title-text': '#2196f3',
    '--btn-secondary-bg': '#64b5f6',
    '--btn-secondary-hover-bg': '#42a5f5',
  },

  blueDark: {
    '--chat-bg': '#0d47a1',
    '--bubble-own-bg': '#1565c0',
    '--bubble-theirs-bg': '#1e88e5',
    '--text-color': '#e3f2fd',
    '--header-bg': '#1976d2',
    '--header-text': '#ffffff',
    '--input-bg': '#1565c0',
    '--button-bg': '#1976d2',
    '--button-hover-bg': '#0d47a1',
    '--sidebar-bg': '#1565c0',
    '--sidebar-text': '#e3f2fd',
    '--title-text': '#bbdefb',
    '--btn-secondary-bg': '#64b5f6',
    '--btn-secondary-hover-bg': '#42a5f5',
  },

  greenLight: {
    '--chat-bg': '#e8f5e9',
    '--bubble-own-bg': '#a5d6a7',
    '--bubble-theirs-bg': '#c8e6c9',
    '--text-color': '#1b5e20',
    '--header-bg': '#4caf50',
    '--header-text': '#ffffff',
    '--input-bg': '#ffffff',
    '--button-bg': '#4caf50',
    '--button-hover-bg': '#388e3c',
    '--sidebar-bg': '#c8e6c9',
    '--sidebar-text': '#1b5e20',
    '--title-text': '#4caf50',
    '--btn-secondary-bg': '#81c784',
    '--btn-secondary-hover-bg': '#66bb6a',
  },

  greenDark: {
    '--chat-bg': '#1b5e20',
    '--bubble-own-bg': '#2e7d32',
    '--bubble-theirs-bg': '#388e3c',
    '--text-color': '#e8f5e9',
    '--header-bg': '#388e3c',
    '--header-text': '#ffffff',
    '--input-bg': '#2e7d32',
    '--button-bg': '#388e3c',
    '--button-hover-bg': '#1b5e20',
    '--sidebar-bg': '#2e7d32',
    '--sidebar-text': '#e8f5e9',
    '--title-text': '#a5d6a7',
    '--btn-secondary-bg': '#81c784',
    '--btn-secondary-hover-bg': '#66bb6a',
  },

  redLight: {
    '--chat-bg': '#ffebee',
    '--bubble-own-bg': '#ef9a9a',
    '--bubble-theirs-bg': '#ffcdd2',
    '--text-color': '#b71c1c',
    '--header-bg': '#f44336',
    '--header-text': '#ffffff',
    '--input-bg': '#ffffff',
    '--button-bg': '#f44336',
    '--button-hover-bg': '#d32f2f',
    '--sidebar-bg': '#ffcdd2',
    '--sidebar-text': '#b71c1c',
    '--title-text': '#f44336',
    '--btn-secondary-bg': '#e57373',
    '--btn-secondary-hover-bg': '#ef5350',
  },

  redDark: {
    '--chat-bg': '#b71c1c',
    '--bubble-own-bg': '#c62828',
    '--bubble-theirs-bg': '#d32f2f',
    '--text-color': '#ffebee',
    '--header-bg': '#d32f2f',
    '--header-text': '#ffffff',
    '--input-bg': '#c62828',
    '--button-bg': '#d32f2f',
    '--button-hover-bg': '#b71c1c',
    '--sidebar-bg': '#c62828',
    '--sidebar-text': '#ffebee',
    '--title-text': '#ef9a9a',
    '--btn-secondary-bg': '#e57373',
    '--btn-secondary-hover-bg': '#ef5350',
  },

  purpleLight: {
    '--chat-bg': '#f3e5f5',
    '--bubble-own-bg': '#ce93d8',
    '--bubble-theirs-bg': '#e1bee7',
    '--text-color': '#4a148c',
    '--header-bg': '#9c27b0',
    '--header-text': '#ffffff',
    '--input-bg': '#ffffff',
    '--button-bg': '#9c27b0',
    '--button-hover-bg': '#7b1fa2',
    '--sidebar-bg': '#e1bee7',
    '--sidebar-text': '#4a148c',
    '--title-text': '#9c27b0',
    '--btn-secondary-bg': '#ba68c8',
    '--btn-secondary-hover-bg': '#ab47bc',
  },

  purpleDark: {
    '--chat-bg': '#4a148c',
    '--bubble-own-bg': '#6a1b9a',
    '--bubble-theirs-bg': '#7b1fa2',
    '--text-color': '#f3e5f5',
    '--header-bg': '#7b1fa2',
    '--header-text': '#ffffff',
    '--input-bg': '#6a1b9a',
    '--button-bg': '#7b1fa2',
    '--button-hover-bg': '#4a148c',
    '--sidebar-bg': '#6a1b9a',
    '--sidebar-text': '#f3e5f5',
    '--title-text': '#ce93d8',
    '--btn-secondary-bg': '#ba68c8',
    '--btn-secondary-hover-bg': '#ab47bc',
  },
};

export default THEMES;
