const THEMES = {
  defaultLight: {
    '--primary-bg-color': '#f5f5f5',
    '--primary-line-color': '#cccccc',
    '--primary-text-color': '#212529',
    '--primary-title-color': '#343A40',
    '--active-contact-bg': '#e9ecef',
    '--chat-bg': '#f5f5f5',
    '--bubble-own-bg': '#cce5ff',
    '--bubble-theirs-bg': '#e9ecef',
    '--text-color': '#212529',
    '--header-bg': '#007bff',
    '--header-text': '#ffffff',
    '--input-bg': '#ffffff',
    '--button-bg': '#007bff',
    '--button-hover-bg': '#0056b3',
    '--title-text': '#007bff',
    '--btn-secondary-bg': '#6c757d',
    '--btn-secondary-hover-bg': '#5a6268',
  },

  defaultDark: {
    '--primary-bg-color': '#343a40',
    '--primary-line-color': '#cccccc',
    '--primary-text-color': '#F8F9FA',
    '--primary-title-color': '#E9ECEF',
    '--active-contact-bg': '#495057',
    '--chat-bg': '#272727ff',
    '--bubble-own-bg': '#2a9df4',
    '--bubble-theirs-bg': '#0d0d4aff',
    '--text-color': '#f1f1f1',
    '--header-bg': '#0d6efd',
    '--header-text': '#ffffff',
    '--input-bg': '#2a2a2a',
    '--button-bg': '#0d6efd',
    '--button-hover-bg': '#084298',
    '--title-text': '#0d6efd',
    '--btn-secondary-bg': '#6c757d',
    '--btn-secondary-hover-bg': '#5a6268',
  },

  blueLight: {
    '--primary-bg-color': '#f5f5f5',
    '--primary-line-color': '#cccccc',
    '--primary-text-color': '#212529',
    '--primary-title-color': '#343A40',
    '--active-contact-bg': '#e9ecef',
    '--chat-bg': '#e3f2fd',
    '--bubble-own-bg': '#90caf9',
    '--bubble-theirs-bg': '#bbdefb',
    '--text-color': '#0d47a1',
    '--header-bg': '#2196f3',
    '--header-text': '#ffffff',
    '--input-bg': '#ffffff',
    '--button-bg': '#2196f3',
    '--button-hover-bg': '#1976d2',
    '--title-text': '#2196f3',
    '--btn-secondary-bg': '#64b5f6',
    '--btn-secondary-hover-bg': '#42a5f5',
  },

  blueDark: {
    '--primary-bg-color': '#343a40',
    '--primary-line-color': '#cccccc',
    '--primary-text-color': '#F8F9FA',
    '--primary-title-color': '#E9ECEF',
    '--active-contact-bg': '#495057',
    '--chat-bg': '#0d47a1',
    '--bubble-own-bg': '#1565c0',
    '--bubble-theirs-bg': '#1e88e5',
    '--text-color': '#e3f2fd',
    '--header-bg': '#1976d2',
    '--header-text': '#ffffff',
    '--input-bg': '#1565c0',
    '--send-button-bg': '#1976d2',
    '--send-button-hover-bg': '#0d47a1',
    '--title-text': '#bbdefb',
    '--btn-secondary-bg': '#64b5f6',
    '--btn-secondary-hover-bg': '#42a5f5',
  },

  greenLight: {
    '--primary-bg-color': '#f5f5f5',
    '--primary-line-color': '#cccccc',
    '--primary-text-color': '#212529',
    '--primary-title-color': '#343A40',
    '--active-contact-bg': '#e9ecef',
    '--chat-bg': '#e8f5e9',
    '--bubble-own-bg': '#a5d6a7',
    '--bubble-theirs-bg': '#c8e6c9',
    '--text-color': '#1b5e20',
    '--header-bg': '#4caf50',
    '--header-text': '#ffffff',
    '--input-bg': '#ffffff',
    '--send-button-bg': '#4caf50',
    '--send-button-hover-bg': '#388e3c',
    '--title-text': '#4caf50',
    '--btn-secondary-bg': '#81c784',
    '--btn-secondary-hover-bg': '#66bb6a',
  },

  greenDark: {
    '--primary-bg-color': '#343a40',
    '--primary-line-color': '#555b4f',
    '--primary-text-color': '#dbe6d0',
    '--primary-title-color': '#c4d3b2',
    '--active-contact-bg': '#3f4a39',
    '--chat-bg': '#152214',
    '--bubble-own-bg': '#2e7d32',
    '--bubble-theirs-bg': '#375a25',
    '--text-color': '#c8d7b7',
    '--header-bg': '#388e3c',
    '--header-text': '#e3f0db',
    '--input-bg': '#2a3b20',
    '--send-button-bg': '#388e3c',
    '--send-button-hover-bg': '#1b5e20',
    '--title-text': '#a5d088',
    '--btn-secondary-bg': '#81c784',
    '--btn-secondary-hover-bg': '#66bb6a',
  },

  redLight: {
    '--primary-bg-color': '#f5f5f5',
    '--primary-line-color': '#cccccc',
    '--primary-text-color': '#212529',
    '--primary-title-color': '#343A40',
    '--active-contact-bg': '#e9ecef',
    '--chat-bg': '#ffebee',
    '--bubble-own-bg': '#ef9a9a',
    '--bubble-theirs-bg': '#ffcdd2',
    '--text-color': '#b71c1c',
    '--header-bg': '#f44336',
    '--header-text': '#ffffff',
    '--input-bg': '#ffffff',
    '--send-button-bg': '#f44336',
    '--send-button-hover-bg': '#d32f2f',
    '--title-text': '#f44336',
    '--btn-secondary-bg': '#e57373',
    '--btn-secondary-hover-bg': '#ef5350',
  },

  redDark: {
    '--primary-bg-color': '#343a40',
    '--primary-line-color': '#6e2727',
    '--primary-text-color': '#f0dcdc',
    '--primary-title-color': '#debebe',
    '--active-contact-bg': '#4b2222',
    '--chat-bg': '#3b1212',
    '--bubble-own-bg': '#7a2a2a',
    '--bubble-theirs-bg': '#6b2020',
    '--text-color': '#f1dbdb',
    '--header-bg': '#8b2f2f',
    '--header-text': '#f7d9d9',
    '--input-bg': '#6b2020',
    '--send-button-bg': '#8b2f2f',
    '--send-button-hover-bg': '#4b1212',
    '--title-text': '#df9c9c',
    '--btn-secondary-bg': '#e57373',
    '--btn-secondary-hover-bg': '#ef5350',
  },

  purpleLight: {
    '--primary-bg-color': '#f5f5f5',
    '--primary-line-color': '#cccccc',
    '--primary-text-color': '#212529',
    '--primary-title-color': '#343A40',
    '--active-contact-bg': '#e9ecef',
    '--chat-bg': '#f3e5f5',
    '--bubble-own-bg': '#ce93d8',
    '--bubble-theirs-bg': '#e1bee7',
    '--text-color': '#4a148c',
    '--header-bg': '#9c27b0',
    '--header-text': '#ffffff',
    '--input-bg': '#ffffff',
    '--send-button-bg': '#9c27b0',
    '--send-button-hover-bg': '#7b1fa2',
    '--title-text': '#9c27b0',
    '--btn-secondary-bg': '#ba68c8',
    '--btn-secondary-hover-bg': '#ab47bc',
  },

  purpleDark: {
    '--primary-bg-color': '#343a40',
    '--primary-line-color': '#cccccc',
    '--primary-text-color': '#F8F9FA',
    '--primary-title-color': '#E9ECEF',
    '--active-contact-bg': '#495057',
    '--chat-bg': '#4a148c',
    '--bubble-own-bg': '#6a1b9a',
    '--bubble-theirs-bg': '#7b1fa2',
    '--text-color': '#f3e5f5',
    '--header-bg': '#7b1fa2',
    '--header-text': '#ffffff',
    '--input-bg': '#6a1b9a',
    '--send-button-bg': '#7b1fa2',
    '--send-button-hover-bg': '#4a148c',
    '--title-text': '#ce93d8',
    '--btn-secondary-bg': '#ba68c8',
    '--btn-secondary-hover-bg': '#ab47bc',
  },
};

export default THEMES;
